### ISSUE TITLE
Not working under Groovyarcade

### ISSUE THREAD

**Issue by retrorepair** [psakhis/86Box4crt#1]
I can't get this to run under groovyarcade which is a shame as it'd be the ideal candidate for a switchres based fork.

It compiles fine but freezes after flickering the screen a few times.

Is there a crashlog or aomething I can enable to help troubleshoot? This fork has potential I think to be amazing

**Comment by psakhis** [comment]
I know. Last updates crash switchres lib.

I have to investigate what happens with last updates because it's working great on windows and kms before this updates.

**Comment by retrorepair** [comment]
I think substring actually had the same issue when he ran a full system update after 6.7, he suspected enforcing the output was the issue

**Comment by psakhis** [comment]
When i builded last version with recent updates, 86box worked but vsync didn't. So i need to check where is the problem

**Comment by psakhis** [comment]
Fixed. Downgrade mesa for vsync issue.
